# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8d6c31b07f7b2601c349f5132c8ac00a5234ee8328fb64e7c12c27835856cf40131cb7d7f6df9e041c3475e4fae386871af28ed811dd1829af6ea6d99ce543

test:
  secret_key_base: e820fe9c41b5a3ff2de3e0aed4a6c5618f5be4a109639ae9c650647af58f5ce19bbff1b1e38fe8002e468a392df957a32695a9cfe26b3c5796ac371537582b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
